name: Build and Publish Binaries

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13  # Match your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Binary
      run: |
        pyinstaller luna_server.spec

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: luna-server-${{ matrix.os }}
        path: dist/luna-server

  publish:
    name: Publish Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.run_number }}
        name: Release ${{ github.run_number }}
        body: Binary release for luna-server
        draft: false
        prerelease: false

    - name: Upload Assets to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/luna-server
        asset_name: luna-server-${{ matrix.os }}.zip
        asset_content_type: application/zip
